name: CI/CD Automated Unit Testing

on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Compile Unit Tests
        # هنا بنأكد على اسم الملف unit_tests.cpp والامتداد بتاعه
        run: g++ unittests.cpp -o run_tests

      - name: Execute Tests
        run: ./run_tests
